import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :hellen, HellenWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Database connection pool tuning for production
# These are defaults that can be overridden via DATABASE_URL or runtime.exs
config :hellen, Hellen.Repo,
  pool_size: 20,
  queue_target: 500,
  queue_interval: 1000

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Hellen.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
